// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZmb42TkvsrUSfTaOhbcCm34_FbBC-8PU',
    appId: '1:879096534098:web:a6a1fd4a8c88070d407b8b',
    messagingSenderId: '879096534098',
    projectId: 'gdsc-firebase-session',
    authDomain: 'gdsc-firebase-session.firebaseapp.com',
    storageBucket: 'gdsc-firebase-session.appspot.com',
    measurementId: 'G-PXL9VVSZF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8IaUJ1V5u_VOtIww7IbWLMWt04VxcpOs',
    appId: '1:879096534098:android:123aa65c073bc1ba407b8b',
    messagingSenderId: '879096534098',
    projectId: 'gdsc-firebase-session',
    storageBucket: 'gdsc-firebase-session.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC40_wKK3xSO-ZSQAgO46N9KUExBxvEZ-I',
    appId: '1:879096534098:ios:3280d1f821a99380407b8b',
    messagingSenderId: '879096534098',
    projectId: 'gdsc-firebase-session',
    storageBucket: 'gdsc-firebase-session.appspot.com',
    iosBundleId: 'com.gdsc.firebaseLesson',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC40_wKK3xSO-ZSQAgO46N9KUExBxvEZ-I',
    appId: '1:879096534098:ios:0e6fa8b0fddb0bc3407b8b',
    messagingSenderId: '879096534098',
    projectId: 'gdsc-firebase-session',
    storageBucket: 'gdsc-firebase-session.appspot.com',
    iosBundleId: 'com.gdsc.firebaseLesson.RunnerTests',
  );
}
